
/*An array containing all the country names in the world:*/
var countries = ["Afghanistan",
"Adhesive",
"Adhesive Tapes",
"Adhesive Super Glues",
"DIY Glues",
"Tape",
"Bike Repairs",
"Double Sided Foam Tape",
"Glue Gun",
"Insulation Tape",
"Silicone Gun",
"Silicone Sealant",
"Stationery Glues and Tape",
"School Glue Sticks",
"Tape Brown",
"Tape Clear",
"Tape Dispenser",
"Tape Packaging",
"Arts",
"Crafts",
"Colouring Products",
"Coloured Pencils Sets",
"Drawing Books",
"Highlighters",
"Multi-purpose Scissors",
"Oil Pastels",
"Paint Marker Pens",
"Sharpeners",
"Wax Crayons",
"Pens Pencils and Markers",
"Ballpoint Pens",
"Erasers",
"Gel Pens",
"Pencil Boxes and Cases",
"Pencil Cases",
"Pencil Leads",
"Pencils",
"Pencils Clutch",
"Audio Visual",
"Audio Devices",
"Bluetooth Earphones",
"Bluetooth Gadgets",
"Bluetooth Headset",
"Bluetooth Speakers",
"Earphones",
"Earplugs",
"Gaming Earphones",
"Gaming Headsets",
"Gaming Speakers",
"Headphones and Microphones",
"Home Theatre Speakers",
"Multimedia  Speakers",
"Portable Speakers",
"Professional Microphones",
"Remote Control",
"Sound Cards",
"Voice Recorder",
"Bluetooth Products",
"Bluetooth Adaptors",
"Bluetooth Keyboards",
"Bluetooth Mini Joystick",
"Bluetooth Mouse",
"Cameras",
"Camcorders",
"Audio Camcorder Tapes",
"Video Camcorder Tapes",
"Dash Cameras",
"Digital Camera",
"Digital Camera Bag",
"Digital Cameras Accessories",
"Digital Cameras Cases",
"Selfie Monopod ",
"Web Camera",
"Car Electronics",
"Car Gadgets",
"Car Power Adapter",
"Car Signal Processors",
"Car Speakers",
"Car Subwoofer",
"Home Car Chargers",
"Displays",
"Monitors",
"Monitor LCD",
"Monitor LED",
"Monitor Touch Screen",
"Line Drivers Extenders",
"HDMI Couplers",
"HDMI Extenders",
"HDMI Hubs and Switches",
"USB Extenders",
"VGA RGB Extenders",
"iPhone Sports Accessories",
"iPod Accessories",
"Ipod Docking",
"Multimedia Players",
"Multimedia TV",
"Multimedia Editing",
"Multimedia Decoders",
"Projectors",
"Projectors and Accessories",
"Input Device (Presenter)",
"Projector Brackets",
"Projector Lamps",
"Projector Screens",
"DJ Equipment",
"Voice Recorder",
"Televisions",
"Televisions Smart Full HD",
"Televisions Smart Ultra HD",
"Televisions Standard Full HD",
"Televisions Standard HD Ready",
"Televisions CRT ",
"Wall Mount Brackets",
"Television Brackets",
"Automotive Products",
"Booster Cables",
"Ratchets Sockets",
"Ratchet Spanner",
"Spanners Sockets",
"Combination Squares",
"Hack Saws",
"Hammers",
"Hand Files",
"Socket Sets",
"Wrenches",
"Tyre Changer Jacks",
"Bike Repairs",
"Bottle Jack",
"Baby Department",
"Baby and Toddler",
"Baby Bathing",
"BabyMoov",
"Baby Feeding",
"Baby Maternity Handbags",
"Baby Out About",
"Baby Sleeping",
"Microwave Baby Bottle Sterilizer",
"Squishy Toys",
"Bags",
"Luggage store",
"Notebook Bags",
"Notebook Cases",
"Notebook Sleeves",
"Notebook Backpacks",
"Notebook Trolley Backpacks",
"Notebook Trolley Bags",
"Student Backpacks",
"Battery",
"Alkaline Batteries ",
"Consumer Batteries",
"Laptop Batteries",
"LIithium Batteries",
"NiMh Batteries",
"Battery Charger",
"Power Banks",
"Solar Power Devices",
"ZINC Batteries",
"Bedroom",
"Bathroom",
"Toilet Bench",
"Health and Beauty",
"Beauty",
"Body Massagers",
"Electric Toothbrushes",
"Fragrances",
"Hair Clippers",
"Hair Dryers",
"Hair Straighteners",
"Hair Trimmers",
"Lady Shavers",
"Men Shavers",
"Books, Pads Carbon",
"Pads",
"Carbon",
"Book Labels",
"Book Covers",
"Book Covers Brown Kraft",
"Book Covers Plastic",
"Book Covers Precut",
"Book Covers Slipons",
"Star Labels",
"Cables Adapters",
"Cable Management",
"Cable Adaptors Convertors",
"Cable Firewire",
"Cable HDMI",
"Cable IDE/EIDE",
"Cable Internal/External",
"Cable Monitor ",
"Cable OTG",
"Cable Power",
"Cable PS/2",
"Cable SCSI",
"Cable Serial ATA",
"Cable USB",
"Cable USB 3.1",
"Cable USB Extension",
"Display Port Cable",
"Parallel/Serial Cables",
"USB Micro Cables",
"USB Mini Cables",
"HDMI Products",
"HDMI Couplers",
"HDMI Extenders",
"HDMI Hubs and Switches",
"DVI",
"Displayport",
"OTG",
"Memory (USB flash-OTG)",
"OTG (Card Reader)",
"USB OTG Adapter",
"Toolkit",
"Test equipment",
"CCTV (Ground Loop Isolator)",
"CCTV BNC Connector",
"CCTV Video Baluns",
"MultiPlugs",
"PowerAdaptors",
"Networking RJ45 connectors",
"Camping",
"Outdoor",
"Tables",
"Chairs",
"Gifting",
"Occasions",
"Braai Accessories",
"Braai Stands",
"Chafing Dishes",
"Humidifiers",
"Knife Sets",
"Outdoor Accessories",
"Salt Grinders",
"Pepper Grinders",
"Scented Candles",
"Camping Chairs",
"Gas Stoves",
"Hose Pipe Fittings",
"CCTV and DVR",
"CCTV",
"CCTV (Bullet Type Camera)",
"CCTV (Camera brackets)",
"CCTV (Camera)",
"CCTV (Covert Camera)",
"CCTV (Dome Camera)",
"CCTV (DVR Microphone)",
"CCTV (DVR) DIY Combo Kit",
"CCTV (DVR) Stand Alone",
"CCTV (Embedded DVR's)",
"CCTV (PC Based DVR Cards)",
"CCTV (PTZ Camera)",
"CCTV (Video Encoder)",
"CCTV IP Server",
"Hard Disk (Surveillance)",
"Hard Disk(Enterprise)",
"Security and Alarm Product",
"Wireless IP Camera",
"IP Cameras",
"CCTV IP Server",
"IP Camera brackets",
"Uninterruptible Power Supply",
"Battery Charger",
"Inverters",
"CD / DVD Cases",
"CD/DVD Wallet",
"Cleaning Kits",
"Generic  Toners",
"Generic Ink Cartridges",
"Ink Toners",
"Media (CD/DVD/Blu-ray)",
"Office Equipment",
"Paper A4 80gsm",
"Photo Paper A4",
"Printer Ink Cartridge",
"Printer Ribbons",
"Printer Toner Cartridge",
"Laminators",
"LED Lighting",
"Shredders",
"Vacuum Sealers",
"Controller (FireWire)",
"Controller (Parallel)",
"Controller (RAID)",
"Controller (SATA)",
"Digital Photo Frame",
"Input Device (Keyboard)",
"Input Device (Mouse wireless)",
"Input Device (Wired Mouse)",
"Input Device(Keyboard+Mouse)",
"Joysticks and Game Controllers",
"Card Printers Accessories",
"Printer (Laser) Accessories",
"POS Thermal Paper",
"Computer Chassis",
"Chassis Cooling Solutions",
"Computer Case",
"Computer Case (Accessories)",
"Computer Case (ITX)",
"Computer Case (Mid-Tower)",
"Gaming Chassis",
"Server (Chassis)",
"Computer Components",
"CPU Heat sink and Fan AMD",
"CPU Heat sink and Fan Hybrid",
"CPU Heat sink and Fan Intel",
"CPU Thermal Pad",
"CPU Thermal Paste",
"CPU-Intel LGA1151",
"CPU-Intel LGA1151 KabyLake",
"Graphics Cards AMD",
"Graphics Cards NVIDIA ",
"Memory (Desktop)",
"Memory (Desktop)-DDR4",
"Motherboard-Intel-LGA1151",
"Optical Drives CD/DVD/Blu-Ray",
"VGA Card Cooling",
"Computer Desktop Systems",
"Desktop Systems-Branded",
"Software Antivirus",
"Software Operating System",
"Software Productivity",
"VGA RGB Extenders",
"Gaming Chairs",
"Gaming Keyboards",
"Gaming Mice",
"Gaming Modifications",
"Hard Drive Accessories",
"Hard Disk Bag",
"Hard Drive Enclosures",
"Hard Disk Docks",
"Hard Drives/Storage",
"Hard Disk (External)",
"Hard Disk (Mobile)",
"Hard Disk (NAS)",
"Hard Disk (SATA)",
"Hard Disk (SSD)",
"Gaming Mouse Pads",
"Mouse Pad",
"Mining Motherboard",
"Power Supplies",
"Electrical Accessories",
"Switches and Sockets)",
"Flush Switches",
"Isolator Switch",
"Plug Tops",
"Surface Switch Socket",
"Cable Clips",
"Cable Ties",
"Downlights Brackets",
"Metal Cutter",
"Nail in Anchors",
"Screw Drivers",
"Solder Iron",
"Solder Wire",
"Spirit Levels",
"Tape Measures",
"Furniture",
"Decor",
"Tables",
"Chairs",
"Home Improvement",
"Action Camera",
"Dash Cameras",
"Electric Scooter",
"Flashlights",
"Remote Controlled Drones",
"Vacuum Cleaners ",
"VR Glasses",
"Mobile and Smartphones",
"Mobile Phones",
"Mobile Smart Phones",
"Tablet PC's",
"USB Flash Sticks",
"USB Flash Sticks 3.0",
"USB Hubs",
"USB Charger",
"USB Ethernet Adaptor",
"Gaming Bags",
"Console Gaming Accessories",
"Gaming Console-Controllers",
"Gaming Console-Games PS3",
"Gaming Console-Games PS4",
"Gaming Console-Games Xbox ",
"Gaming Console-Headsets",
"Chisels",
"Club Hammer",
"Discus padlocks",
"Latches",
"Paint Brushes",
"Paint Rollers",
"Pliers",
"Hex Keysets",
"Hole Saw Blades",
"Screw Drivers",
"Gardening Tools",
"LED Flood Lights",
"LED Lamps",
"Plumbing Tools",
"Security Locksets",
"Chafing Dishes",
"Fans - Summer Seasonal",
"Heaters - Winter Seasonal",
"Homeware",
"Appliances",
"Blenders",
"Juicers",
"Hand Stick Blenders",
"Jug Blenders",
"Coffee Appliances",
"Coffee Makers",
"Coffee Pods",
"Milk Frother",
"Cooking Appliances",
"Air Fryers",
"Deep Fryers",
"Electric Frying Pans",
"Grills Griddles",
"Hot Plates - Stoves",
"Multi Food Machines",
"Pressure Cookers",
"Cookware",
"Hot Trays",
"Microwaves",
"Mini Ovens",
"Pots and Pans",
"Food Preparation",
"Food Processors",
"Food Steamers",
"Ice Cream Maker",
"Kettle/Toaster Combo",
"Toasters",
"Homekeeping Products",
"Floor Cleaners",
"Garment Steamers",
"Vacuum Cleaners ",
"Washing Lines",
"Window Cleaner",
"Kitchen Accessories",
"Cereal Dispensers",
"Dustbins",
"Glass Jugs",
"Kitchen Scale",
"Laundry Bins",
"Pastry / Meat Brush",
"TeVo Products",
"Urns / Water Heating Buckets",
"Vacuum Flasks",
"Cordless Kettles",
"Knives and Utensils",
"Utensil Sets",
"Utility Knives and blades",
"Serveware",
"Champagne Glass Sets",
"Speciality Appliances",
"Sandwich Toasters",
"Memory (SD Flash)Class 10",
"Memory (SD Flash)Class 4",
"Magnetic Disk Media",
"Memory (MicroSD Flash)",
"Blackberry Phone Covers",
"Google Nexus Covers",
"iPhone 6 Covers",
"iPhone 6 Covers + Battery ",
"iPhone 6 Screen Protectors",
"iPhone Covers",
"iPhone Covers + Battery",
"iPhone Covers + Keyboard",
"iPhone Screen Protectors",
"Samsung Galaxy Note Covers",
"Samsung S2 Covers",
"Samsung S3 Covers",
"Samsung S4 Covers",
"Samsung S5 Covers",
"Samsung S5 Covers +Battery",
"Samsung S5 Screen Protectors",
"Samsung S6 Covers",
"Various Phone Covers",
"Networking",
"KVM Switches",
"Networking (KVM Accessories)",
"Networking (KVM Switch)",
"Modems and Routers",
"Access Point -PoE",
"Access Points, Bridges",
"ADSL Broadband Modems",
"ADSL Broadband Routers",
"Broadband Routers -3G/LTE",
"SIM Modems - 3G / 4G",
"Wireless Adaptors - PCMCIA ",
"Wireless Antennas",
"Networking-Active",
"Ethernet Switches Gigabit",
"Ethernet Switches PoE",
"Network Interface Card (NIC)",
"Networking (Couplers)",
"Networking (Misc Equipment)",
"Networking RJ45 connectors",
"Networking(Media Converters)",
"Networking(Powerline)",
"Power over Ethernet (PoE)",
"USB Ethernet Adaptor",
"Networking-Passive",
"Networking Patch Panels",
"Patch Cable-Cat5",
"Patch Cable-Cat6",
"Rack Cabinets 19 Accessories",
"Server (Cabinet Accessories)",
"Server (Cabinet)",
"Server (Chassis)",
"Laptop Batteries",
"Notebook Cooling Pads ",
"Notebook  Power units",
"Notebook Bags and Cases",
"Hard Disk Docks",
"Gaming Range Notebook",
"Mid-Range Notebook",
"Office Machine Accessories",
"Calculators",
"School Calculators",
"Scientific Calculators",
"Filing and Folders",
"Filing Sleeves and Pockets",
"Flip Files",
"Lever Arch Storage",
"Report Folders",
"A5 Quad Margin Books",
"Accessible Files",
"Ballpoint Pens",
"Correction Fluids",
"Counter Books",
"Desk Cubes and Refills",
"Filing Sleeves and Pockets",
"Flip Files",
"Plumbing Tools",
"Point of Sale",
"Point of Sale and Accessories",
"POS Cash Drawers",
"POS CCD Scanners",
"POS Counterfeit Detectors",
"POS Laser Scanners",
"POS Printers",
"POS Thermal Label Printer",
"Printer (Dot Matrix)",
"Card Printers Accessories",
"Mouse",
"Mice",
"Mirco SD Cards",
"Mirco SD Cards Adaptors",
"Keyboards",
"SD Cards",
"SD Mirco Cards Adaptors"
];

/*initiate the autocomplete function on the "myInput" element, and pass along the countries array as possible autocomplete values:*/
autocomplete(document.getElementById("myInput"), countries);

